// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADoDK1Q9cCNQgh9yd8D1Zjm49-DzidRMA',
    appId: '1:812221084773:web:0a43ff6605caffd624c28c',
    messagingSenderId: '812221084773',
    projectId: 'portal-isuapp',
    authDomain: 'portal-isuapp.firebaseapp.com',
    storageBucket: 'portal-isuapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY0Av5wpArZ2fMHeS7FyUtDPEj2M-NcE0',
    appId: '1:812221084773:android:0fcc433717234e8b24c28c',
    messagingSenderId: '812221084773',
    projectId: 'portal-isuapp',
    storageBucket: 'portal-isuapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGbBIAYvRtc217qubZe8O7uaOVdkffh4',
    appId: '1:812221084773:ios:3a867c1e1a587c3b24c28c',
    messagingSenderId: '812221084773',
    projectId: 'portal-isuapp',
    storageBucket: 'portal-isuapp.appspot.com',
    iosClientId: '812221084773-60sm776mhvce61pohs1k72m7ujootu1e.apps.googleusercontent.com',
    iosBundleId: 'com.csbd.portal.isuapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGbBIAYvRtc217qubZe8O7uaOVdkffh4',
    appId: '1:812221084773:ios:3a867c1e1a587c3b24c28c',
    messagingSenderId: '812221084773',
    projectId: 'portal-isuapp',
    storageBucket: 'portal-isuapp.appspot.com',
    iosClientId: '812221084773-60sm776mhvce61pohs1k72m7ujootu1e.apps.googleusercontent.com',
    iosBundleId: 'com.csbd.portal.isuapp',
  );
}
